### ISSUE TITLE
build error and the solution that worked for me

### ISSUE THREAD

**Issue by hsalameh** [zugaldia/android-robocar#12]
I got a bunch of  build error in three modules: libcv, libhardware, and libsoftware. It is the same error in all three, and it looks something like this:

```
robocar\libhardware\src\androidTest\java\com\zugaldia\robocar\hardware\ExampleInstrumentedTest.java:4: error: package android.support.test does not exist
import android.support.test.InstrumentationRegistry;
```
The solution that worked for me was to add the following to all three build.gradle files of the above mentioned modules under the dependencies sections
```
 androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
```

**Comment by zugaldia** [comment]
Thank you @hsalameh for the report! We just PR'ed the changes you suggested, it looks like some testing dependencies were accidentally removed.
