### ISSUE TITLE
Create basic docs

### ISSUE THREAD

**Issue by zugaldia** [zugaldia/android-robocar#2]
Let's use the wiki (https://github.com/zugaldia/android-robocar/wiki) to have the basics covered, for example, how to build a basic robocar from scratch and install the demo app on it.

**Comment by zugaldia** [comment]
A picture of the first prototype for the docs:

![img_20170225_154112](https://cloud.githubusercontent.com/assets/6964/23334669/afefdc60-fb71-11e6-91ca-f8d1c32df33e.jpg)

**Comment by ultraon** [comment]
Hello, It's a great job!!! Could you please add hardware list for that car?

**Comment by zugaldia** [comment]
@ultraon First version is up and running: https://github.com/zugaldia/android-robocar/wiki/Hardware. Let me know what you think!
