### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gitterpro** [zugaldia/android-robocar#24]
Hi, I'm having trouble building both the mobile and robocar apps, the build project went OK but when trying to run "app", it has the following error in Android Studio.  Appreciate your help!

Information:Gradle tasks [:app:assembleDebug]
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/libjniopencv_shape.so
  	File1: /Users/me/.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/opencv/3.2.0-1.3/2a562ef4d4408c1dea5d4190b6bbd151a83c8eae/opencv-3.2.0-1.3-android-x86.jar
  	File2: /Users/me/AndroidStudioProjects/android-robocar-master/robocar/libcv/build/intermediates/bundles/default/jni
Information:BUILD FAILED

**Comment by hsalameh** [comment]
@gitterpro If you are trying to deploy the robocar/app to a phone emulator, most probably it's not going to work. You need to deploy it to an actual Raspberry Pi 3 device running Android Things.
